import loginManager as login

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    login.set_email_info("lucas3rocks@gmail.com", "flpb bmmf xchd mjdx")
    login.set_db_info("coen174", "user", "localhost", "root", "Passed_Word")
    login.initialize_database()

    print("Starting Unit Tests for loginManager.py. True=passed, False=failed")

    print("Test 1:")
    print(not login.create_account("lvanderheijden@scu.edu", "Lucas", "lvanderheijden", "12345"))
    print("Test 2:")
    print(not login.create_account("lvanderheijden@scu.edu", "Lucas", "lucas3rocks@gmail.com", "12345"))
    print("Test 3:")
    print(not login.create_account("lvanderheijden@scu.edu", "Lucas", "lucas3rocks@gmail.com", "12345"))
    print("Test 4:")
    print(login.create_account("lvanderheijden@scu.edu", "Lucas", "lvanderheijden@scu.edu", "12345"))
    print("Test 5:")
    print(not login.auth_account("lucas3rocks@gmail.com", "hello"))
    print("Test 6:")
    print(not login.create_account("lvanderheijden@scu.edu", "Lucas", "lvanderheijden@scu.edu", "21321"))

    print("Input the code sent by email.")
    auth_code = input()
    print("Test 7:")
    print(not login.auth_account("lucas3rocks@gmail.com", auth_code))
    print("Test 8:")
    print(login.auth_account("lvanderheijden@scu.edu", auth_code))
    print("Test 9:")
    print(not login.auth_account("lvanderheijden@scu.edu", "12345"))
    print("Test 10:")
    print(not login.auth_account("lvanderheijden@scu.edu", auth_code))
    print("Test 11:")
    print(not login.login("lucas3rocks@gmail.com", "hello"))
    print("Test 12:")
    print(not login.login("lvanderheijden@scu.edu", "hello"))
    print("Test 13:")
    print(login.login("lvanderheijden@scu.edu", "12345"))
    login.clean_account_list()
    print("Test 14:")
    print(login.change_password("lvanderheijden@scu.edu", "54321"))
    print("Test 15:")
    print(not login.login("lvanderheijden@scu.edu", "12345"))
    print("Test 16:")
    print(login.login("lvanderheijden@scu.edu", "54321"))
    print("Test 17:")
    print(login.delete_account("lvanderheijden@scu.edu"))
    print("Test 18:")
    print(not login.login("lvanderheijden@scu.edu", "54321"))
